apiVersion: v2
appVersion: '32.71.3'
description: Universal dependency update tool that fits into your workflows.
name: renovate
version: '32.71.4'
icon: https://docs.renovatebot.com/assets/images/logo.png
home: https://github.com/renovatebot/renovate
keywords:
  - automated
  - dependencies
  - dependency
  - management
  - update
sources:
  - https://github.com/renovatebot/renovate
  - https://github.com/renovatebot/helm-charts
maintainers:
  - name: JamieMagee
    email: jamie.magee@gmail.com
  - name: viceice
    email: michael.kriese@visualon.de
  - name: rarkins
    email: rhys@arkins.net
annotations:
  artifacthub.io/license: AGPL-3.0-only
  artifacthub.io/images: |
    - name: renovate
      image: renovate/renovate:32.71.3
  artifacthub.io/links: |
    - name: docs
      url: https://docs.renovatebot.com
dependencies:
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    version: 14.8.11
    condition: redis.enabled
